// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.0
// source: api/secrets/v1/server.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_SECRETS_MANAGER      Protocol = 1
	Protocol_VAULT                Protocol = 2
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "SECRETS_MANAGER",
		2: "VAULT",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"SECRETS_MANAGER":      1,
		"VAULT":                2,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_api_secrets_v1_server_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_api_secrets_v1_server_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_api_secrets_v1_server_proto_rawDescGZIP(), []int{0}
}

// fetch
type FetchSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol Protocol `protobuf:"varint,2,opt,name=protocol,proto3,enum=secrets.Protocol" json:"protocol,omitempty"`
}

func (x *FetchSecretRequest) Reset() {
	*x = FetchSecretRequest{}
	mi := &file_api_secrets_v1_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSecretRequest) ProtoMessage() {}

func (x *FetchSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_secrets_v1_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSecretRequest.ProtoReflect.Descriptor instead.
func (*FetchSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_secrets_v1_server_proto_rawDescGZIP(), []int{0}
}

func (x *FetchSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FetchSecretRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

type FetchSecretResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *FetchSecretResponse) Reset() {
	*x = FetchSecretResponse{}
	mi := &file_api_secrets_v1_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSecretResponse) ProtoMessage() {}

func (x *FetchSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_secrets_v1_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSecretResponse.ProtoReflect.Descriptor instead.
func (*FetchSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_secrets_v1_server_proto_rawDescGZIP(), []int{1}
}

func (x *FetchSecretResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_api_secrets_v1_server_proto protoreflect.FileDescriptor

var file_api_secrets_v1_server_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x2f, 0x76, 0x31,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x22, 0x57, 0x0a, 0x12, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x2d, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22,
	0x2d, 0x0a, 0x13, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x2a, 0x44,
	0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x52,
	0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x45, 0x43, 0x52, 0x45, 0x54, 0x53, 0x5f,
	0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x41, 0x55,
	0x4c, 0x54, 0x10, 0x02, 0x32, 0x53, 0x0a, 0x07, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x12,
	0x48, 0x0a, 0x0b, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x1b,
	0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x73, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x61, 0x70, 0x69,
	0x2f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_secrets_v1_server_proto_rawDescOnce sync.Once
	file_api_secrets_v1_server_proto_rawDescData = file_api_secrets_v1_server_proto_rawDesc
)

func file_api_secrets_v1_server_proto_rawDescGZIP() []byte {
	file_api_secrets_v1_server_proto_rawDescOnce.Do(func() {
		file_api_secrets_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_secrets_v1_server_proto_rawDescData)
	})
	return file_api_secrets_v1_server_proto_rawDescData
}

var file_api_secrets_v1_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_secrets_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_secrets_v1_server_proto_goTypes = []any{
	(Protocol)(0),               // 0: secrets.Protocol
	(*FetchSecretRequest)(nil),  // 1: secrets.FetchSecretRequest
	(*FetchSecretResponse)(nil), // 2: secrets.FetchSecretResponse
}
var file_api_secrets_v1_server_proto_depIdxs = []int32{
	0, // 0: secrets.FetchSecretRequest.protocol:type_name -> secrets.Protocol
	1, // 1: secrets.Secrets.FetchSecret:input_type -> secrets.FetchSecretRequest
	2, // 2: secrets.Secrets.FetchSecret:output_type -> secrets.FetchSecretResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_secrets_v1_server_proto_init() }
func file_api_secrets_v1_server_proto_init() {
	if File_api_secrets_v1_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_secrets_v1_server_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_secrets_v1_server_proto_goTypes,
		DependencyIndexes: file_api_secrets_v1_server_proto_depIdxs,
		EnumInfos:         file_api_secrets_v1_server_proto_enumTypes,
		MessageInfos:      file_api_secrets_v1_server_proto_msgTypes,
	}.Build()
	File_api_secrets_v1_server_proto = out.File
	file_api_secrets_v1_server_proto_rawDesc = nil
	file_api_secrets_v1_server_proto_goTypes = nil
	file_api_secrets_v1_server_proto_depIdxs = nil
}
